### ISSUE TITLE
Namespace Creation and Edit Issues

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy-dev#253]
Here's a summary of issues found in a first pass of the namespace creation and edit. Details follow the list. Automated testing still pending.

# Summary

- On namespace creation, account entry is not validated like it is on namespace edit
- On namespace creation, no error messages are given for invalid or missing input
- Users can remove themselves as the only (non-RedHat) owner of a namespace. Should that be allowed?

## No Account ID Validation on Create

When creating a namespace:
![nscreate1](https://user-images.githubusercontent.com/34982/74057648-5f4b5400-49b2-11ea-9145-7bbe2154679e.jpg)

When editing a namespace:
![nsedit1](https://user-images.githubusercontent.com/34982/74057646-5eb2bd80-49b2-11ea-9758-da70953bfe7e.jpg)

## No error messages on namespace creation

- No error if the name is not entered
- No error if the account field is not entered
- Validation problems above also generate no visible errors

## Can remove last user and orphan namespace

- You can remove yourself as the only owner of a namespace
- After removing all owners, you still have an edit option for the namespace
- After removing all owners, you can still open the edit page for the namespace
- After removing all owners, you can still attempt to save edits to the namespace, causing 403 API errors internally

**Comment by romanblanco** [comment]
> On namespace creation, account entry is not validated like it is on namespace edit 

fixed in: https://github.com/ansible/ansible-hub-ui/pull/99

**Comment by romanblanco** [comment]
> Users can remove themselves as the only (non-RedHat) owner of a namespace. Should that be allowed?

Not sure about this. I know they are not allowed to remove `system:partner-engineer` owner (https://github.com/ansible/galaxy-api/pull/149#discussion_r374636221).

@chouseknecht @cutwater is there a scenario, where the option to remove themselves as namespace owner should be available?

**Comment by ironfroggy** [comment]
@romanblanco Namespaces still become orphaned if an owner accidentally removes themselves, but they still have access to the edit option, to go to the namespace edit form, and to make changes and click the Save button. It only fails internally, with a 403 from the API, and no visible error to the user.

**Comment by ironfroggy** [comment]
Everything looks good now!
